### ISSUE TITLE
Getting "Docker daemon not running on this host error"

### ISSUE THREAD

**Issue by pkyeck** [kabisa/jenkins-docker#8]
I get an error saying:
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

Any idea why this could be? Running the same command as `jenkins` user directly on the machine works as expected.

Jenkins logs (I added some debug logs):

``` bash
[test-docker] $ /bin/sh -xe /tmp/hudson2675390311624763568.sh
+ run-containerized npm test

user: jenkins
path: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
which docker? /usr/bin/docker
workspace: /var/lib/jenkins/workspace/test-docker
pwd: /var/lib/jenkins/workspace/test-docker

Building test-docker Docker image, this can take some...
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by pascalw** [comment]
Hi @pkyeck. Couple of things that come to mind:
- Does your Jenkins by any chance set a `DOCKER_HOST` variable?
- Have you restarted your Jenkins instance after adding the `jenkins` user to the `docker` group?

My guess is that your problem is the latter. Changes in groups only take affect for new processes (don't recall the details, but that's the gists if I recall).

**Comment by pkyeck** [comment]
@pascalw thanks for pointing me in the right direction ... seems that it was the group-addition b/c restarting the server fixed the "problem". :+1:

**Comment by pascalw** [comment]
Great, let me know if you have any other questions!
